
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scorecard.quay.io
  resources:
  - scorecardhelloworlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scorecard.quay.io
  resources:
  - scorecardhelloworlds/finalizers
  verbs:
  - update
- apiGroups:
  - scorecard.quay.io
  resources:
  - scorecardhelloworlds/status
  verbs:
  - get
  - patch
  - update
