# permissions for end users to view scorecardhelloworlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scorecardhelloworld-viewer-role
rules:
- apiGroups:
  - scorecard.quay.io
  resources:
  - scorecardhelloworlds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scorecard.quay.io
  resources:
  - scorecardhelloworlds/status
  verbs:
  - get
