apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: scorecard-helloworld.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ScorecardHelloWorld is the Schema for the scorecardhelloworlds
        API
      displayName: Scorecard Hello World
      kind: ScorecardHelloWorld
      name: scorecardhelloworlds.scorecard.quay.io
      version: v1alpha1
  description: Scorecard HelloWorld
  displayName: scorecard-helloworld
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keyword1
  - keyword2
  - scorecard
  - test
  - functional
  - helloworld
  links:
  - name: Scorecard Helloworld
    url: https://scorecard-helloworld.domain
  maturity: alpha
  provider:
    name: Red Hat
    url: www.redhat.com
  version: 0.0.0
